# Generated by Django 4.1.5 on 2023-02-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0006_alter_yoga_name_alter_yoga_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=300)),
                ('name2', models.CharField(max_length=300)),
                ('name3', models.CharField(max_length=300)),
                ('picture1', models.ImageField(upload_to='yogaimg')),
                ('picture2', models.ImageField(upload_to='yogaimg')),
                ('picture3', models.ImageField(upload_to='yogaimg')),
                ('problem', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Yoga',
        ),
    ]
